title: WisTex United Docs
description: A starter template for WisTex United Docs
theme: just-the-docs

url: https://github.com/wistex-united/wistex-united.github.io
aux_links:
  Source Code: https://github.com/wistex-united/wistex-united.github.io

nav_external_links:
  - title: BHuman Public Wiki
    url: https://docs.b-human.de/
    opens_in_new_tab: true

  - title: WisTex on GitHub
    url: https://github.com/wistex-united

color_scheme: wis-tex

callouts:
  hint:
    title: üí° Hint
    color: grey-md
    opacity: 0.25

  info:
    title: ‚ÑπÔ∏è Info
    color: blue
    opacity: 0.2
  
  attention:
    title: ‚ö†Ô∏è Attention
    color: yellow
    opacity: 0.2

  caution:
    title: ‚ùóÔ∏è Caution
    color: red
    opacity: 0.15

logo: /assets/images/WisTex-United-Logo-250x250.png
favicon_ico: /assets/images/WisTex-United-Logo-220x220.png
